### ISSUE TITLE
high resolution(1024) train

### ISSUE THREAD

**Issue by gunerhui** [lyndonzheng/TFill#8]
how to train high resolution(1024)  model
edit parameters--load_size' 542*2 '--fine_size' 512*2 --fixed_size' 256*2
and train images are in larger resolutions
that's ok?

**Comment by lyndonzheng** [comment]
Hi @gunerhui, thanks for your interesting. The first stage must be a fixed resolution $256\times256$, while the second stage can be $1024\times1024$. However, you may need to downsample the feature to smaller features size in the second stage. Otherwise, the self-attention in AAL module will be large, resulting in highly expensive compute cost.
